parameters:
#    cluddy_application.example.class: Cluddy\ApplicationBundle\Example

services:
#    cluddy_application.example:
#        class: %cluddy_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
